config/routes.rb
Rails.application.routes.draw do
root 'quotes#index' 
resources :quotes 
get 'about', to: 'quotes#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :saying, presence: true, length: { maximum: 140, minimum: 3}
	validates :author, presence: true, length: { maximum: 50, minimum: 3}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quote = Quote.order("RANDOM()").first
  end

  

  def create
    @quote = Quote.create(quote_params)
    if @quote.invalid?
      flash[:error] = '<strong>Could not save</strong> the date you entered is invalid.'
    end
    redirect_to root_path
  end

  def about
  end
  private

  def quote_params
    params.require(:quote).permit(:saying, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   

    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
     
    <title>Splurty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path do %>
        <div class="circle">
          <br />
          Let us
          <br />
          help you
          <br />
         podcast!
      </div>
      <% end %>
    </div>
      <div class="col col-sm-4 hidden-xs-down slogan">
        You should be podcasting. And we want to help.
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
      <!-- Button trigger modal -->
      <%= link_to 'Contribute', '#', data: {toggle: 'modal', target: '#myModal'} %>
      &nbsp; &nbsp;
      <%= link_to 'About', about_path %>  
      </div>
    

    
   
  </div>
  </header>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelleby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">Contribute Your Quote</h4>
          </div>
          
          <%= simple_form_for Quote.new do |f| %>
           <div class="modal-body">
            <%= f.input :saying, label: "What is the saying you want to add?", placeholder: "Podcasting is pressing buttons and praying you're right." %>
            <%= f.input :author, label: "Who is the author of the quote?", placeholder: "Johnny Soundlevel" %>
  <br />
  
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Create', class: 'btn btn-danger' %>
              </div>
            <% end %>
            
          </div>
        </div>
      </div>
   


    <hr/>

    <br class="clear" />

    <div class="container">
      <% if flash[:error].present? %>
        <div class ="col-10 offset-1 alert alert-danger">
          <%= flash[:error].html_safe %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer">
      <div class="container">
         <div class="col-12 col-sm-6">
          <%= link_to "Hit me with some more knowledge.", root_path, class: 'next-quote' %>
        </div>
        <div class="col-12 col-sm-6 footer-blurb">
          Proudly hacked by &nbsp; <a href="https://wilsonhorrell.netlify.com/"> Wilson Horrell 
        </div>
      </div>
    </div>
  </div>
   
    
 
  </body>
</html>

app/views/quotes/about.html.erb
<div class="col-10 offset-1 about">
	<h1>About Lift Heavy Run Long®</h1>
	


	<div class="col-12 col-sm-6 about">
		<%= image_tag 'hosts.jpg', class: 'img-fluid' %>
	</div>

	<p>
	<br> <a target="_blank" href="https://www.liftheavyrunlong.com/"><font color="#8C0000">The Lift Heavy Run Long® Podcast</font></a> was formed by Wilson Horrell and Von Ralls as a way to encourage people to make fitness a priority while building community and making sure that each individual felt as comfortable as possible within the Lift Heavy Run Long® Community. </p>
	
	<p>Wilson and Von are passionate about their podcast and they feel strongly about the potential that comes with making connections with people. They are always encouraging people to start their own podcasts and are open to sharing any and all of their ideas with anyone who is willing to listen. They are also happy to share and laugh at their mistakes along the way because there have been plenty! </p>
	
	<p>If you are interested in following our podcast or have any quesitons about starting your own, you can find us at <a target="_blank" href="https://www.liftheavyrunlong.com/"><font color="#8C0000">LiftHeavyRunLong.com</font>.</a>   
	</p>

	<div class="row">
		<div class="col-12 col-sm-4">
			<%= image_tag 'behindCamerNoFilter.jpg', class: 'img-fluid' %>
			
		</div>

		<div class="col-12 col-sm-7 offset-sm-1">
			<h2 class="text-center">Wilson Horrell</h2>
			
			<p>
			Wilson Horrell is an computer programmer, podcast producer, entrepreneur, writer and family man. He has owned his owned business for sixteen years and has a passion for learning new things.</p>
		</div>
	</div>
		<br class="clear" />
		

	<div class="row">
		<div class="col-12 col-sm-4" style="padding-top:30px;">
			<%= image_tag 'podcastMic.jpg', class: 'img-fluid' %>

	 </div>
  <div class="col-12 col-sm-7 offset-sm-1">
	<h2 class="text-center"> Von Ralls</h2>
	
	<p>
		Von Ralls is an experienced web developer, podcast host and owner of one of the most successful Crossfit gyms in DeSoto County. Von is a husband and father of three children who enjoys helping working with others and helping them reach their goals.
	</p>
	</div>
</div>


<br class="clear" />
<br />
<br />
<br />
<br />

app/views/quotes/index.html.erb
<h2>
	<span> SPLURTY / No. <%= @quote.id %> </span>
	Here's the <u>best unsolicited podcast advice</u> you can get! </h2>
	<br>
<h1> <%= @quote.saying %> </h1>
<br>

<h2 class="float-left"> -<%= @quote.author %></h2>

<br class="clear" />
<br />
<br />
<br />

app/views/quotes/new.html.erb
<h1> Enter your quote details</h1>
<%= simple_form_for @quote do |f| %>
	<%= f.input :saying %>
	<%= f.input :author %>
	<br />
	<%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>